### ISSUE TITLE
今天拉下最新的仓库，发现有个任务Debug会解析失败

### ISSUE THREAD

**Issue by yu-echo** [syoius/MaaYuan#113]
[maa.log](https://github.com/user-attachments/files/17729251/maa.log)

![image](https://github.com/user-attachments/assets/dcbaa4e7-30ce-41e4-8180-dbe4953d7c6d)

/resource/base/pipeline/daily/base-events.json
删掉就正常了，我看了下内容也没错的地方

**Comment by syoius** [comment]
怪欸，我这边拉main没问题🤔 可能是你没force pull，有资源结构调整然后就冲突了？

**Comment by yu-echo** [comment]
> 怪欸，我这边拉main没问题🤔 可能是你没force pull，有资源结构调整然后就冲突了？

我删掉本地重新克隆远程仓库也是一样，后续再试试
