### ISSUE TITLE
派遣据点的我先咕了，先做点简单的练练（循环逻辑有问题

### ISSUE THREAD

**Issue by yu-echo** [syoius/MaaYuan#41]
根据选项，判断队伍上限，上限达标即认为做完，
但是存在领取奖励情况，还是要把各个据点遍历一遍，看看是不是有未领取的
单次循环半成品如下
[Get_About.json](https://github.com/user-attachments/files/17553414/Get_About.json)
[interface.json](https://github.com/user-attachments/files/17553463/interface.json)

**Comment by syoius** [comment]
@yu-echo 我感觉据点派遣可以都做成独立的任务（在GUI那边就分开显示、分开勾选）
比如列表里 □ 派遣-洛阳，□ 派遣-寿春，□ 派遣-广陵（建筑材料的那个地方？）
使用者具体要挂&收哪个就自己勾哪个
这样只检测对应据点是“该收了/未派遣/派遣中（结束任务）”
用起来和写起来都更方便直观些

**Comment by yu-echo** [comment]
单独显示是方便，这样直接去对应的据点处理就可以了
